version: "3.9"
services:
  ros2:
    build: .
    network_mode: host
    ipc: host
#    runtime: nvidia
    volumes:
      - /home/kev/ros:/home/ros
      - /home/kev/cubie-1:/ros2
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    tty: true
    environment:
<<<<<<< HEAD
      - DISPLAY
#      - NVIDIA_VISIBLE_DEVICES=all
#      - NVIDIA_DRIVER_CAPABILITIES=all
=======
      - DISPLAY
>>>>>>> 2e95c0d158e92e1a67af19e059f853e9e42f8f18
