version: "3.9"
services:
  ros2:
    build: .
    # restart: no
    # ports: 
    #   - "3332:3332"
    #   - "11811:11811" # node discoverer
    #   - "32650:32650"
    #   - "32651:32651"
    #   - "32662:32662"
    #   - "32663:32663"
    network_mode: host
    ipc: host
#    runtime: nvidia
    volumes:
      - /home/kev/ros:/home/ros
      - /home/kev/cubie-1:/ros2
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    tty: true
    environment:
      - DISPLAY
#      - NVIDIA_VISIBLE_DEVICES=all
#      - NVIDIA_DRIVER_CAPABILITIES=all
